#!/usr/bin/env python3
"""
This file contains a function
"""
from typing import List
import asyncio
async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    """
    The function collects 10 numbers generated by the async_generator
    function and returns them

    Args: Does not receive arguments
    """
    return [num async for num in async_generator()]
